import { test, expect } from '@playwright/test';

test.describe('ToDo Application', () => {
  const uniqueId = Date.now().toString();
  const titleText = `E2E Playwright Task ${uniqueId}`;
  
  test('Complete CRUD flow for a ToDo item', async ({ page }) => {
    // 1. Visit the home page
    await page.goto('/');
    
    // 2. Verify that the app loaded correctly
    await expect(page.locator('h1').first()).toHaveText('My Tasks');
    
    // 3. Add a new ToDo
    // Click "New Task" button (if empty state, it might not be visible, but it is in the header)
    await page.click('.new-task-btn');
    
    // Fill the form
    await page.fill('#title', titleText);
    await page.fill('#description', 'This was automatically generated by Playwright.');
    await page.click('button[type="submit"]');
    
    // 4. Verify the item appeared in the list
    const todoItem = page.locator('.todo-item', { hasText: titleText });
    await expect(todoItem).toBeVisible();
    await expect(todoItem.locator('.todo-description')).toHaveText('This was automatically generated by Playwright.');
    
    // 5. Edit the ToDo
    await todoItem.locator('.edit-btn').click();
    
    const updatedTitle = `${titleText} - Edited`;
    await page.fill('#title', updatedTitle);
    await page.click('button[type="submit"]');
    
    // Match the new edited title
    const editedTodoItem = page.locator('.todo-item', { hasText: updatedTitle });
    await expect(editedTodoItem).toBeVisible();
    
    // 6. Complete the ToDo
    const checkboxLabel = editedTodoItem.locator('.checkmark');
    await checkboxLabel.click();
    
    // Verify it changed to completed state
    await expect(editedTodoItem).toHaveClass(/is-completed/);
    
    // 7. Delete the ToDo
    await editedTodoItem.locator('.delete-btn').click();
    
    // Verify it implies disappearance
    await expect(editedTodoItem).toBeHidden();
  });
});
